"'&Dotbhalfcircle;' <> '.dotbhalfcircle.';",
"'&Dotlhalfcircle;' <> '.dotlhalfcircle.';",
"'&Dotrhalfcircle;' <> '.dotrhalfcircle.';",
"'&Dotthalfcircle;' <> '.dotthalfcircle.';",
"'&Asteriskpseud;' <> '.asterisk-pseud.';",
"'&Bothorzbrace;' <> '.BHorizBrace.';",
"'&Brketclosest;' <> '.brket close-st.';",
"'&Dottedcircle;' <> '.dottedcircle.';",
"'&Parenclosest;' <> '.paren close-st.';",
"'&Rectversolid;' <> '.rect-ver-solid.';",
"'&Tophorzbrace;' <> '.THorizBrace.';",
"'&Brketopenst;' <> '.brket open-st.';",
"'&Circlesolid;' <> '.circle-solid.';",
"'&Lhalfcircle;' <> '.lhalfcircle.';",
"'&Parenopenst;' <> '.paren open-st.';",
"'&Rhalfcircle;' <> '.rhalfcircle.';",
"'&Centerline;' <> '.centerline.';",
"'&Ovalhollow;' <> '.oval-hollow.';",
"'&Ovalsolid;' <> '.oval-solid.';",
"'&Rectsolid;' <> '.rect-solid.';",
"'&Hslashed;' <> '.h slashed.';",
"'&Quadbond;' <> '.quadbond.';",
"'&Dagger;' <> '.dagger-dbl.';",
"'&Oslash;' <> '.O slashed.';",
"'&becaus;' <> '.BECAUSE.';",
"'&brvbar;' <> '.linevert split.';",
"'&ccedil;' <> '.cedilla.';",
"'&compfn;' <> '.smallcircle.';",
"'&curren;' <> '.sunburst.';",
"'&dagger;' <> '.dagger.';",
"'&divide;' <> '.div.';",
"'&female;' <> '.female.';",
"'&forall;' <> '.A-inverted.';",
"'&hearts;' <> '.heart.';",
"'&middot;' <> '.multidot.';",
"'&mnplus;' <> '.-+.';",
"'&nequiv;' <> '.notident.';",
"'&ominus;' <> '.crclbar.';",
"'&oslash;' <> '.o slashed.';",
"'&permil;' <> '.Salinity.';",
"'&plusmn;' <> '.+-.';",
"'&rlarr2;' <> '.revreaction.';",
"'&square;' <> '.quadrature.';",
"'&there4;' <> '.thrfore.';",
"'&verbar;' <> '.vertline.';",
"'&aelig;' <> '.ae butted.';",
"'&angst;' <> '.ANG.';",
"'&aring;' <> '.ang.';",
"'&blank;' <> '.hoarfrost.';",
"'&boxdl;' <> '.right brkt-top.';",
"'&boxdr;' <> '.left brkt-top.';",
"'&boxul;' <> '.right brkt-bot.';",
"'&boxur;' <> '.left brkt-bot.';",
"'&boxvl;' <> '.perp-left.';",
"'&boxvr;' <> '.perp-right.';",
"'&check;' <> '.check mark.';",
"'&diams;' <> '.diamond-solid.';",
"'&dtrif;' <> '.tangle-soliddn.';",
"'&empty;' <> '.0.';",
"'&equiv;' <> '.ident.';",
"'&esdot;' <> '.apprch.';",
"'&exist;' <> '.E-backward.';",
"'&image;' <> '.Fourier.';",
"'&infin;' <> '.infin.';",
"'&nabla;' <> '.gradient.';",
"'&natur;' <> '.music-natural.';",
"'&notin;' <> '.epsilon slash.';",
"'&oelig;' <> '.oe butted.';",
"'&oplus;' <> '.sym.';",
"'&pound;' <> '.English Pound.';",
"'&sharp;' <> '.music-sharp.';",
"'&starf;' <> '.star-solid.';",
"'&tilde;' <> '.about.';",
"'&times;' <> '.times.';",
"'&trade;' <> '.TM.';",
"'&utrif;' <> '.tangle-solidup.';",
"'&xcirc;' <> '.largecircle.';",
"'&OHgr;' <> '.OMEGA.';",
"'&PHgr;' <> '.PHI.';",
"'&PSgr;' <> '.PSI.';",
"'&THgr;' <> '.THETA.';",
"'&boxH;' <> '.dbd.';",
"'&bsol;' <> '.backslash.';",
"'&bull;' <> '.cndot.';",
"'&cent;' <> '.cent.';",
"'&cong;' <> '.congruent.';",
"'&copy;' <> '.COPYRGT.';",
"'&dArr;' <> '.arrow-down dbl.';",
"'&darr;' <> '.dwnarw.';",
"'&diam;' <> '.diamond.';",
"'&eegr;' <> '.eta.';",
"'&flat;' <> '.music-flat.';",
"'&fnof;' <> '.function.';",
"'&gsim;' <> '.gtorsim.';",
"'&isin;' <> '.di-elect cons.';",
"'&khgr;' <> '.chi.';",
"'&larr;' <> '.rarw.';",
"'&lsim;' <> '.ltorsim.';",
"'&male;' <> '.male.';",
"'&ocir;' <> '.circleincircle.';",
"'&odot;' <> '.circle-w/dot.';",
"'&ohgr;' <> '.omega.';",
"'&para;' <> '.paragraph.';",
"'&part;' <> '.differential.';",
"'&perp;' <> '.perp.';",
"'&phgr;' <> '.phi.';",
"'&prop;' <> '.varies.';",
"'&psgr;' <> '.psi.';",
"'&rarr;' <> '.fwdarw.';",
"'&rect;' <> '.rect-hollow.';",
"'&sect;' <> '.sctn.';",
"'&sime;' <> '.perspectiveto.';",
"'&squf;' <> '.box-solid.';",
"'&star;' <> '.star.';",
"'&thgr;' <> '.theta.';",
"'&uarr;' <> '.uparw.';",
"'&Dgr;' <> '.DELTA.';",
"'&Egr;' <> '.EPSILON.';",
"'&Ggr;' <> '.GAMMA.';",
"'&Lgr;' <> '.LAMBDA.';",
"'&Sgr;' <> '.SIGMA.';",
"'&Ugr;' <> '.UPSILON.';",
"'&Xgr;' <> '.XI.';",
"'&agr;' <> '.alpha.';",
"'&ang;' <> '.angle.';",
"'&bgr;' <> '.beta.';",
"'&cap;' <> '.andgate.';",
"'&cir;' <> '.circle.';",
"'&cup;' <> '.orgate.';",
"'&deg;' <> '.degree.';",
"'&dgr;' <> '.delta.';",
"'&egr;' <> '.epsilon.';",
"'&ggr;' <> '.gamma.';",
"'&igr;' <> '.iota.';",
"'&int;' <> '.intg.';",
"'&kgr;' <> '.kappa.';",
"'&lgr;' <> '.lambda.';",
"'&mgr;' <> '.mu.';",
"'&ngr;' <> '.nu.';",
"'&ngt;' <> '.notgreaterthan.';",
"'&nlt;' <> '.notlessthan.';",
"'&ogr;' <> '.omicron.';",
"'&par;' <> '.parallel.';",
"'&pgr;' <> '.pi.';",
"'&reg;' <> '.RTM.';",
"'&rgr;' <> '.rho.';",
"'&sgr;' <> '.sigma.';",
"'&sub;' <> '.OR right.';",
"'&sup;' <> '.OR left.';",
"'&tgr;' <> '.tau.';",
"'&ugr;' <> '.upsilon.';",
"'&xgr;' <> '.xi.';",
"'&yen;' <> '.Yen.';",
"'&zgr;' <> '.zeta.';",
"'&Pi;' <> '.PI.';",
"'&ap;' <> '.apprxeq.';",
"'&gE;' <> '.gtoreq.';",
"'&lE;' <> '.ltoreq.';",
"'&ne;' <> '.noteq.';",
